### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by octavz** [adevinta/zoe#24]
I really want to give zoe a chance and recommend to my colleagues, seems to do some things right, but 4 months later I am coming back to it and I still don't see how I can use it, after filling an issue then about the same thing.

There is no command line configuration, there is not even a hint in the README on how to configure it to connect to a cluster.

The file configuration is obscure(what is a k8s runner, consumption with lambda, not sure many need these features...)  and difficult to understand, supposing one knows where to look for it, I didn't even bother this time to configure it). 

Please do something to make this usable for the rest of us, thank you.

**Comment by tangi75** [comment]
Have you looked at https://adevinta.github.io/zoe/basics/prepare/ ?

**Comment by octavz** [comment]
For me this kafka client is nothing more than `tar` or `cat` tool and I don't read "the manual" for those either, 
I did read the README on github and https://adevinta.github.io/zoe/ (the first page) and couldn't find any useful info. 
Is my bad I didn't look more.

However, I work a lot with kafka in dockers (integration tests) or proxied to localhost on various ports(think k8s port forward) static configurations is useless for me and probably for others in my situation as well. 
I really want to do: `zoe  my-broker:9092 ....` and go from here. 

You can close the issue, is just a feedback from a wannabe user, I am not trying to push anything, but I would really want to try it for my use cases.
Thank you.

**Comment by tangi75** [comment]
Static configuration is not mandatory. You may look at https://adevinta.github.io/zoe/guides/configuration/guide/

**Comment by wlezzar** [comment]
Hi @octavz thanks for the valuable feedback. 

Zoe is really focused on shareable configuration that you write once and forget about it. You would then point to it using aliases. Even for a Kafka behind a proxy or in docker, I guess you can still use a static configuration file as their addresses are often the same, aren't they?

If you really don't want static configuration, you can also use environment variables are @tangi75 pointed out in the docs in the section `Overriding configuration values using environment variables`. You can do something like:

```bash
export ZOE_CONFIG_OVERRIDE={"clusters": {"default": {"props": {"bootstrap.servers": "custom.endpoint:9092"}}}}
zoe topics list
```

Zoe takes a pretty different approach from other tooling. That's why I would advise at least walking through [The Katacoda basic scenario](https://www.katacoda.com/wlezzar/courses/zoe) directly from your browser. It's super fast and automatic and it gives you a good idea on zoe's usage.

If you still feel some difficulty using the tool, we would be happy to hear your feedback on how we can simplify it. Makes sense?

**Comment by octavz** [comment]
sorry for late reply, proxying things will not cahnge the hists will change the ports, IT wil also assign random ports, itbseems quite verbose and prone to error overriding the config with a json. I would simply expect `zoe host:9092` to work.
